# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Dr. Maximilian Capraro
tagline:             Personal Website & Blog
url:                 http://capraro.net/poole
paginate:            1000
baseurl:             http://capraro.net/poole

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Dr. Maximilian Capraro
  url:               http://capraro.net
  email:             max@capraro.net

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
